const API_BASE=window.RAVIXO_API_BASE||'/api',TOKEN_KEY='ravixo_token';let currentUser=null,currentPosts=[],selectedPost=null,selectedMedia=null,authMode='login',selectedChatUser=null,chatPoll=null,notificationPoll=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),initials=n=>(String(n||'RV').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'RV'),money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v)||0),token=()=>localStorage.getItem(TOKEN_KEY);
function status(m,error=false){const e=$('#status');e.textContent=m||'';e.className='status'+(error?' error':'');if(m)setTimeout(()=>{e.textContent='';e.className='status'},4000)}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token())h.Authorization=`Bearer ${token()}`;let r;try{r=await fetch(API_BASE+path,{...opt,headers:h})}catch{throw new Error('Tidak dapat terhubung ke server RAVIXO.')}const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={error:'Server mengirim respons yang tidak valid.'}}if(r.status===401){localStorage.removeItem(TOKEN_KEY);currentUser=null;updateUserUI()}if(!r.ok)throw new Error(d.error||`API error (${r.status})`);return d}
function open(id){$('#'+id)?.classList.remove('hidden')}function close(id){$('#'+id)?.classList.add('hidden')}function requireLogin(){if(currentUser)return true;open('authModal');status('Silakan masuk terlebih dahulu.',true);return false}
function startNotificationPolling(){if(notificationPoll)clearInterval(notificationPoll);updateNotificationBadge();notificationPoll=setInterval(updateNotificationBadge,5000)}
function stopNotificationPolling(){if(notificationPoll)clearInterval(notificationPoll);notificationPoll=null;$('#notificationBadge')?.classList.add('hidden')}
function updateUserUI(){const name=currentUser?.display_name||'Tamu RAVIXO',u=currentUser?'@'+currentUser.username:'Belum login',i=initials(name);$('#sideName').textContent=name;$('#sideUsername').textContent=u;$('#sideAvatar').textContent=i;$('#composerAvatar').textContent=i;$('#profileBtn').textContent=i;$('#authSideBtn').textContent=currentUser?'Keluar':'Masuk / Daftar'}
async function loadMe(){if(!token()){updateUserUI();return}try{currentUser=(await api('/me')).user;updateUserUI()}catch{localStorage.removeItem(TOKEN_KEY);currentUser=null;updateUserUI()}}
function mediaHTML(p){if(!p.media_url)return '<div class="media brandmedia"><b>RAVIXO</b><small>Share your story. Build your audience.</small></div>';const url=esc(p.media_url);return p.media_type==='video'?`<video class="media realmedia" src="${url}" controls preload="metadata"></video>`:`<img class="media realmedia" src="${url}" alt="Media postingan" loading="lazy">`}
function postCard(p){const liked=!!p.liked;return `<article class="post" data-post-id="${esc(p.id)}"><div class="head"><span class="avatar">${esc(initials(p.display_name||p.username))}</span><div><b>${esc(p.display_name||p.username||'Pengguna RAVIXO')}</b><small>${new Date(p.created_at).toLocaleString('id-ID')} · 🌎 Publik</small></div></div><p>${esc(p.caption||'')}</p>${mediaHTML(p)}<div class="stats">❤️ ${Number(p.likes_count)||0}　 💬 ${Number(p.comments_count)||0} komentar　 ↗ ${Number(p.shares_count)||0} dibagikan　 👁 ${Number(p.views_count)||0}</div><div class="actions"><button class="like-btn" data-id="${esc(p.id)}">${liked?'❤️ Disukai':'❤️ Suka'}</button><button class="comment-btn" data-id="${esc(p.id)}">💬 Komentar</button><button class="share-btn" data-id="${esc(p.id)}">↗ Bagikan</button></div></article>`}
async function loadFeed(q=''){const feed=$('#feed');feed.innerHTML='<div class="loading">Memuat feed RAVIXO...</div>';try{const d=await api('/posts?limit=50'+(q?'&q='+encodeURIComponent(q):''));currentPosts=d.posts||[];feed.innerHTML=currentPosts.length?currentPosts.map(postCard).join(''):'<div class="panel empty">Belum ada postingan.</div>';attachPostEvents()}catch(e){feed.innerHTML='<div class="panel empty">Feed gagal dimuat.</div>';status(e.message,true)}}
function attachPostEvents(){$$('.like-btn').forEach(b=>b.onclick=()=>likePost(b.dataset.id,b));$$('.comment-btn').forEach(b=>b.onclick=()=>showComments(b.dataset.id));$$('.share-btn').forEach(b=>b.onclick=()=>sharePost(b.dataset.id));const seen=new Set();const obs='IntersectionObserver' in window?new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){const id=x.target.dataset.postId;if(!seen.has(id)){seen.add(id);api(`/posts/${id}/view`,{method:'POST'}).catch(()=>{});}}}),{threshold:.5}):null;$$('.post').forEach(c=>obs?obs.observe(c):null)}
async function likePost(id,b){if(!requireLogin())return;try{await api(`/posts/${id}/like`,{method:b.textContent.includes('Disukai')?'DELETE':'POST'});await loadFeed($('#searchInput').value.trim())}catch(e){status(e.message,true)}}
async function sharePost(id){if(!requireLogin())return;try{await api(`/posts/${id}/share`,{method:'POST',body:JSON.stringify({share_type:'internal'})});status('Postingan berhasil dibagikan.');await loadFeed($('#searchInput').value.trim())}catch(e){status(e.message,true)}}
async function showComments(id){selectedPost=id;open('commentModal');$('#commentContent').innerHTML='<div class="loading">Memuat komentar...</div>';try{const d=await api(`/posts/${id}/comments`);$('#commentContent').innerHTML=(d.comments||[]).map(c=>`<div class="comment"><b>${esc(c.display_name||c.username)}</b><p>${esc(c.body)}</p><small>${new Date(c.created_at).toLocaleString('id-ID')}</small></div>`).join('')||'<p class="muted">Belum ada komentar.</p>'}catch(e){$('#commentContent').innerHTML=`<p>${esc(e.message)}</p>`}}
async function createPost(kind='text'){if(!requireLogin())return;selectedMedia=null;$('#captionInput').value='';$('#mediaPreview').innerHTML='';$('#composeTitle').textContent=kind==='text'?'Buat postingan':kind==='image'?'Tambah foto':'Tambah video';open('composeModal');if(kind!=='text'){ $('#mediaInput').accept=kind==='image'?'image/*':'video/*';$('#mediaInput').click()}}
async function uploadMedia(file){const fd=new FormData();fd.append('media',file);const h={};if(token())h.Authorization=`Bearer ${token()}`;const r=await fetch(API_BASE+'/upload',{method:'POST',headers:h,body:fd});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Upload gagal.');return d}
$('#mediaInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(f.size>100*1024*1024)return status('Ukuran file maksimal 100 MB.',true);selectedMedia=f;$('#composeTitle').textContent=f.type.startsWith('video/')?'Tambah video':'Tambah foto';$('#mediaPreview').innerHTML=f.type.startsWith('video/')?`<video controls src="${URL.createObjectURL(f)}"></video>`:`<img src="${URL.createObjectURL(f)}" alt="Preview">`;open('composeModal')});
$('#composeForm').onsubmit=async e=>{e.preventDefault();try{let media_url=null,media_type=null;if(selectedMedia){status('Mengunggah media...');const u=await uploadMedia(selectedMedia);media_url=u.url;media_type=u.media_type}const caption=$('#captionInput').value.trim();if(!caption&&!media_url)return status('Isi caption atau pilih media.',true);await api('/posts',{method:'POST',body:JSON.stringify({caption,visibility:'public',media_url,media_type})});close('composeModal');selectedMedia=null;$('#mediaInput').value='';status('Postingan berhasil dibuat.');await loadFeed()}catch(e){status(e.message,true)}};
$('#commentForm').onsubmit=async e=>{e.preventDefault();if(!requireLogin())return;const body=$('#commentInput').value.trim();if(!body)return;try{await api(`/posts/${selectedPost}/comments`,{method:'POST',body:JSON.stringify({body})});$('#commentInput').value='';await showComments(selectedPost);await loadFeed($('#searchInput').value.trim())}catch(e){status(e.message,true)}};
async function auth(e){e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(authMode==='register'&&(!$('[id=displayName]').value.trim()||!$('#username').value.trim()))return $('#authMessage').textContent='Nama dan username wajib diisi.';try{const body=authMode==='login'?{email,password}:{email,password,display_name:$('#displayName').value.trim(),username:$('#username').value.trim()};const d=await api('/auth/'+authMode,{method:'POST',body:JSON.stringify(body)});localStorage.setItem(TOKEN_KEY,d.token);currentUser=d.user;updateUserUI();startNotificationPolling();close('authModal');status(authMode==='login'?'Berhasil masuk.':'Akun berhasil dibuat.');await loadFeed()}catch(e){$('#authMessage').textContent=e.message}}
function setAuthMode(m){authMode=m;$('#loginTab').classList.toggle('selected',m==='login');$('#registerTab').classList.toggle('selected',m==='register');$('#displayNameWrap').classList.toggle('hidden',m==='login');$('#usernameWrap').classList.toggle('hidden',m==='login');$('#authSubmit').textContent=m==='login'?'Masuk':'Daftar';$('#authPassword').autocomplete=m==='login'?'current-password':'new-password';$('#authMessage').textContent=''}
async function loadMessageUsers(q=''){if(!requireLogin())return;const list=$('#messageUserList');list.innerHTML='<div class=\"loading\">Mencari pengguna...</div>';try{const d=await api('/messages/users?q='+encodeURIComponent(q));list.innerHTML=(d.users||[]).map(u=>`<button class=\"message-user\" data-user-id=\"${u.id}\"><span class=\"avatar\">${initials(u.display_name)}</span><span><b>${esc(u.display_name)}</b><small>@${esc(u.username)}</small></span></button>`).join('')||'<p class=\"muted\">Pengguna tidak ditemukan.</p>';$$('.message-user').forEach(b=>b.onclick=()=>selectChatUser(Number(b.dataset.userId)));}catch(e){list.innerHTML=`<p class=\"muted\">${esc(e.message)}</p>`}}
async function selectChatUser(id){if(!currentUser)return;try{const d=await api('/messages/'+id);selectedChatUser=d.user;$('#chatHeader').innerHTML=`<b>${esc(d.user.display_name)}</b><small>@${esc(d.user.username)} · Pesan pribadi</small>`;$('#messageInput').disabled=false;$('#messageForm button').disabled=false;renderChat(d.messages||[]);startChatPolling();}catch(e){status(e.message,true)}}
function renderChat(messages){const box=$('#chatMessages');box.innerHTML=(messages||[]).map(m=>`<div class=\"chat-bubble ${String(m.sender_id)===String(currentUser.id)?'mine':'theirs'}\"><p>${esc(m.body)}</p><small>${new Date(m.created_at).toLocaleString('id-ID',{dateStyle:'short',timeStyle:'short'})}</small></div>`).join('')||'<p class=\"muted\">Belum ada pesan. Kirim pesan pertama.</p>';box.scrollTop=box.scrollHeight}
async function refreshChat(){if(!selectedChatUser||!currentUser)return;try{const d=await api('/messages/'+selectedChatUser.id);renderChat(d.messages||[]);}catch{}}
function startChatPolling(){if(chatPoll)clearInterval(chatPoll);chatPoll=setInterval(()=>{if(!$('#messageModal').classList.contains('hidden'))refreshChat();},5000)}
function stopChatPolling(){if(chatPoll){clearInterval(chatPoll);chatPoll=null}}
function openMessages(){if(!requireLogin())return;open('messageModal');selectedChatUser=null;$('#chatHeader').innerHTML='<b>Pilih pengguna</b><small>Pesan pribadi hanya terlihat oleh pengirim dan penerima.</small>';$('#chatMessages').innerHTML='<p class=\"muted\">Pilih pengguna untuk membuka percakapan.</p>';$('#messageInput').value='';$('#messageInput').disabled=true;$('#messageForm button').disabled=true;loadMessageUsers();}

async function loadCreator(){if(!requireLogin())return;open('creatorModal');$('#creatorContent').innerHTML='Memuat...';try{const d=await api('/creator/dashboard'),c=d.creator;if(!c)return $('#creatorContent').innerHTML='<p>Akun kreator belum tersedia.</p>';$('#creatorContent').innerHTML=`<div class="creator-stat"><small>Saldo</small><strong>${money(c.balance)}</strong></div><div class="creator-stat"><small>Menunggu</small><strong>${money(c.pending_balance)}</strong></div><div class="creator-stat"><small>Total</small><strong>${money(c.lifetime_earnings)}</strong></div><label>Jumlah pencairan<input id="payoutAmount" type="number" min="1" step="1000" placeholder="Rp"></label><button id="payoutBtn" class="primary">Ajukan Pencairan</button>`;$('#payoutBtn').onclick=async()=>{const amount=Number($('#payoutAmount').value);if(!Number.isFinite(amount)||amount<=0)return status('Jumlah pencairan tidak valid.',true);try{await api('/creator/payouts',{method:'POST',body:JSON.stringify({amount})});status('Permintaan pencairan dibuat.');close('creatorModal');await loadEarnings()}catch(e){status(e.message,true)}}}catch(e){$('#creatorContent').innerHTML=`<p>${esc(e.message)}</p>`}}
async function loadEarnings(){if(!currentUser)return;try{const c=(await api('/creator/dashboard')).creator;if(c){$('#earningsBalance').textContent=money(c.balance);$('#earningsNote').textContent=`Total penghasilan: ${money(c.lifetime_earnings)}`;const target=Math.max(Number(c.lifetime_earnings),1);$('#earningsBar').style.width=Math.min(100,Number(c.balance)/target*100)+'%'}}catch{}}
async function updateNotificationBadge(){if(!currentUser)return;try{const d=await api('/notifications');const badge=$('#notificationBadge');const n=Number(d.unread_count||0);badge.textContent=n>99?'99+':String(n);badge.classList.toggle('hidden',n===0);}catch{}}
async function loadNotifications(){if(!requireLogin())return;open('notificationModal');const b=$('#notificationContent');try{const d=await api('/notifications');b.innerHTML=(d.notifications||[]).map(n=>`<div class="notification-item"><b>${esc(n.type||'Notifikasi')}</b><p>${esc(n.message||'Aktivitas baru')}</p><small>${new Date(n.created_at).toLocaleString('id-ID')}</small></div>`).join('')||'<p>Belum ada notifikasi.</p>';await api('/notifications/read',{method:'POST'});$('#notificationBadge').classList.add('hidden');}catch(e){b.innerHTML=`<p>${esc(e.message)}</p>`}}
function showView(v){if(v==='home')return loadFeed();if(v==='videos'||v==='photos'){const type=v==='videos'?'video':'image';$('#feed').innerHTML=currentPosts.filter(p=>p.media_type===type).map(postCard).join('')||'<div class="panel empty">Belum ada konten.</div>';attachPostEvents();return}if(v==='creator')return loadCreator();if(v==='notifications')return loadNotifications();if(v==='messages')return openMessages();if(v==='settings'){if(!requireLogin())return;$('#settingsName').value=currentUser?.display_name||'';$('#settingsUsername').value=currentUser?.username||'';return open('settingsModal')}if(v==='friends'){return $('#feed').innerHTML='<div class="panel empty"><h3>👥 Teman</h3><p>Daftar teman dan sistem pertemanan siap dikembangkan pada endpoint sosial berikutnya.</p></div>'}}
$('#messageUserSearch').addEventListener('input',e=>loadMessageUsers(e.target.value.trim()));$('#messageForm').onsubmit=async e=>{e.preventDefault();if(!selectedChatUser||!requireLogin())return;const body=$('#messageInput').value.trim();if(!body)return;const btn=$('#messageForm button');btn.disabled=true;try{await api('/messages',{method:'POST',body:JSON.stringify({receiver_id:selectedChatUser.id,body})});$('#messageInput').value='';await refreshChat();}catch(err){status(err.message,true)}finally{btn.disabled=false;$('#messageInput').focus()}};$('#authForm').onsubmit=auth;$('#loginTab').onclick=()=>setAuthMode('login');$('#registerTab').onclick=()=>setAuthMode('register');$('#authSideBtn').onclick=()=>{if(currentUser){localStorage.removeItem(TOKEN_KEY);currentUser=null;stopNotificationPolling();updateUserUI();status('Anda sudah keluar.');loadFeed()}else open('authModal')};$('#profileBtn').onclick=()=>currentUser?loadCreator():open('authModal');$('#composerInput').onclick=()=>createPost('text');$('#photoBtn').onclick=()=>createPost('image');$('#videoBtn').onclick=()=>createPost('video');$('#chooseMedia').onclick=()=>$('#mediaInput').click();$('#monetizeBtn').onclick=loadCreator;$('#dashboardBtn').onclick=loadCreator;$('#earningsBtn').onclick=loadCreator;$('#notificationBtn').onclick=loadNotifications;$('#messageBtn').onclick=openMessages;$('#mainNav').onclick=e=>{const a=e.target.closest('a[data-view]');if(!a)return;e.preventDefault();$$('#mainNav a').forEach(x=>x.classList.remove('active'));a.classList.add('active');showView(a.dataset.view)};$$('[data-close]').forEach(b=>b.onclick=()=>{if(b.dataset.close==='messageModal')stopChatPolling();close(b.dataset.close)});$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m){if(m.id==='messageModal')stopChatPolling();m.classList.add('hidden')}}));$('#searchInput').addEventListener('input',e=>loadFeed(e.target.value.trim()));
(async()=>{updateUserUI();await loadMe();await loadFeed();await loadEarnings()})();
